#!/bin/bash

# This code runs Alpine3D for multiple years ASSUMING paths to files are correct.

BASE_PATH=''
USER_PATH="/home/user"
WATERSHED_PATH="/Watershed"
SIMULATION_PATH="/Alpine3D_simulation1"
BASE_PATH+=$USER_PATH$WATERSHED_PATH$SIMULATION_PATH

for i in 1964 1967; 
  do echo $i; 
  printf "[General]
BUFFER_SIZE = 370
BUFF_BEFORE = 1.5
BUFF_GRIDS = 10

[Input]
COORDSYS = UTM
COORDPARAM = 12N
TIME_ZONE = -7.00

METEO = SMET

METEOPATH = $BASE_PATH/input/smet_files/ERA5_data
METEOPATH_RECURSIVE = true

GRID2D = ARC
GRID2DPATH = $BASE_PATH/input/surface-grids/noisy-included/
GRID2DEXT = .dem


DEM = ARC
DEMFILE = $BASE_PATH/input/surface-grids/noisy-included/dem.asc


SLOPE_ALGORITHM = CORRIPIO
COMPUTE_IN_LOCAL_COORDS = FALSE

LANDUSE = ARC
LANDUSEFILE = $BASE_PATH/input/surface-grids/noisy-included/dem.lus

POI = SMET
POIFILE = $BASE_PATH/input/surface-grids/noisy-included/dem.poi
CATCHMENT_NUMBERING = TAUDEM

SNOW = SMET
SNOWPATH = $BASE_PATH/input/snofiles


[Snowpack]
CALCULATION_STEP_LENGTH = 60.000
ROUGHNESS_LENGTH = 0.002
HEIGHT_OF_METEO_VALUES = 2.0
HEIGHT_OF_WIND_VALUE = 2.0
ENFORCE_MEASURED_SNOW_HEIGHTS = FALSE
SW_MODE = INCOMING
ATMOSPHERIC_STABILITY = NEUTRAL
CANOPY = FALSE
MEAS_TSS = FALSE
CHANGE_BC = FALSE
SNP_SOIL = TRUE

[SnowpackAdvanced]
NUMBER_SLOPES = 1
HN_DENSITY = PARAMETERIZED
HN_DENSITY_PARAMETERIZATION = ZWART

[Alpine3D]
LATERAL_FLOW = FALSE
GLACIER_KATABATIC_FLOW = FALSE

[EBalance]
Terrain_Radiation = TRUE
Terrain_Radiation_Method = SIMPLE

[TechSnow]
SNOW_GROOMING = FALSE
SNOW_PRODUCTION = FALSE

[Filters]
ENABLE_METEO_FILTERS = TRUE
ENABLE_TIME_FILTERS = TRUE

[Interpolations1D]
ENABLE_RESAMPLING = TRUE
WINDOW_SIZE = 43200
PSUM::RESAMPLE = ACCUMULATE
PSUM::ACCUMULATE::PERIOD = 3600

[Interpolations2D]
TA::ALGORITHMS = ODKRIG_LAPSE IDW_LAPSE AVG_LAPSE
TA::AVG_LAPSE::RATE = -0.0075
TA::AVG_LAPSE::SOFT = FALSE
TA::IDW_LAPSE::RATE = -0.0075
TA::IDW_LAPSE::SOFT = FALSE
TA::ODKRIG_LAPSE::SOFT = FALSE

RH::ALGORITHMS = LISTON_RH IDW_LAPSE AVG
RH::IDW_LAPSE::SOFT = FALSE
RH::LISTON_RH::SOFT = FALSE

VW::ALGORITHMS = LISTON_WIND
VW::LISTON_WIND::SOFT = FALSE
DW::ALGORITHMS = LISTON_WIND
DW::LISTON_WIND::SOFT = FALSE

ISWR::ALGORITHMS = SWRAD
ISWR::SWRAD::SHADING = TRUE
ISWR::SWRAD::PROJECT_ON_SLOPE = TRUE

ILWR::ALGORITHMS = ILWR_EPS
ILWR::ILWR_EPS::MULTILINEAR = TRUE
ILWR::ILWR_EPS::SOFT = FALSE

PSUM::ALGORITHMS = IDW_LAPSE AVG_LAPSE
PSUM::AVG_LAPSE::RATE = 0.0016
PSUM::AVG_LAPSE::FRAC = TRUE
PSUM::CST::VALUE = 0
PSUM::IDW_LAPSE::RATE = 0.0016
PSUM::IDW_LAPSE::FRAC = TRUE

PSUM_PH::ALGORITHMS = PPHASE
PSUM_PH::PPHASE::TYPE = RANGE
PSUM_PH::PPHASE::SNOW = 274.35
PSUM_PH::PPHASE::RAIN = 276.35
P::ALGORITHMS = STD_PRESS
P::STD_PRESS::USE_RESIDUALS = FALSE

[Output]
COORDSYS = UTM
COORDPARAM = 12N
TIME_ZONE = -7.00
GRIDS_WRITE = TRUE
GRID2D = ARC
GRID2DPATH = $BASE_PATH/output/grid-files/WY${i}
GRIDS_START = 0.0
GRIDS_DAYS_BETWEEN = 1 ;1=1day ;calculate grid data only daily 
GRIDS_PARAMETERS = HS SWE TA TSS

MASK_GLACIERS = FALSE
WRITE_RUNOFF_GRIDS = FALSE
METEO = SMET

METEOPATH = $BASE_PATH/output/meteo/WY${i}
WRITE_PROCESSED_METEO = TRUE

EXPERIMENT = TEST_A3D
SNOW_WRITE = FALSE
PROF_WRITE = TRUE
PROF_FORMAT = PRO
PROF_START = 0
PROF_DAYS_BETWEEN = .25
HARDNESS_IN_NEWTON = FALSE
TS_WRITE = TRUE
TS_FORMAT = SMET
TS_START = 0
TS_DAYS_BETWEEN = 0.125
AVGSUM_TIME_SERIES = TRUE
CUMSUM_MASS = FALSE
PRECIP_RATES = TRUE
OUT_CANOPY = FALSE
OUT_HAZ = FALSE
OUT_SOILEB = FALSE
OUT_HEAT = TRUE
OUT_T = TRUE
OUT_LW = TRUE
OUT_SW = TRUE
OUT_MASS = TRUE
OUT_METEO = TRUE
OUT_STAB = TRUE

[InputEditing]
ENABLE_TIMESERIES_EDITING = TRUE

[SnowpackSeaice]
CHECK_INITIAL_CONDITIONS = FALSE
" > SouthForkFlathead_Alpine3D_${i}.ini;




cd ../WatershedBasin/
echo "$PWD"
j=$(($i-1))

python -c "import grisMet2snowpackMetIO as gr2sno; gr2sno.era2metio(${i}, precip_factor=1.5, air_temp_offset=0)"
cd ../Alpine3D_simulation1
echo "$PWD"
alpine3d --startdate=${j}-10-01T00:00 --enddate=${i}-9-30T00:00 --np-snowpack=48 --np-ebalance=4 --iofile=./setup/SouthForkFlathead_Alpine3D_${i}.ini

  done
  

